/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Food.Order;
import Listeners.Navigator;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import kitchen.Kitchen;

public class OrdersList extends javax.swing.JPanel
{
    ArrayList<Order> orders;
    Navigator navigator;
    Kitchen kitchen;
    int orderCount = 0;
    /**
     * Creates new form OrdersList
     */
    public OrdersList(Kitchen kitchen, Navigator navigator)
    {
        initComponents();
        setSize(388, 400);
        this.navigator = navigator;
        this.kitchen = kitchen;
        
        
        //Waits for an order to be placed
        while(kitchen.getOrders().isEmpty())
        {
            System.out.println("Waiting for order to be placed...");
            try
            {
                Thread.sleep(5000);
            } catch (InterruptedException ex)
            {
                Logger.getLogger(OrdersList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        populateOrders(kitchen.getOrders(), navigator);
        repaint();
        revalidate();        

    }
    

    public void populateOrders(ArrayList<Order> orders, Navigator navigator)
    {
        for(Order order : orders)
        {
            add(new OrderNumberLabel(Integer.toString(order.getOrderNumber()), navigator));
            orderCount++;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
