/*
 * CSCE 4444
 * 
 * 
 */
package GUI;

import Listeners.Navigator;

public class OrderNumberLabel extends javax.swing.JPanel
{
    
    Navigator navigator;
    OrdersList ordersList;

    /**
     * Creates new form TableNumberLabel
     */
    public OrderNumberLabel(String orderNumString, Navigator navigator)
    {
        initComponents();
        setSize(388, 50);
        this.navigator = navigator;
        
        orderNumber.setText("Order # " + orderNumString);
       
    }
    
    public OrderNumberLabel(OrdersList ordersList, String orderNumString)
    {
        initComponents();
        setSize(388, 50);
        this.ordersList = ordersList;
        
        orderNumber.setText("Order # " + orderNumString);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        orderNumber = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        orderNumber.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        orderNumber.setForeground(new java.awt.Color(255, 255, 0));
        orderNumber.setMaximumSize(new java.awt.Dimension(388, 50));
        orderNumber.setMinimumSize(new java.awt.Dimension(388, 50));
        orderNumber.setPreferredSize(new java.awt.Dimension(388, 50));
        orderNumber.setSize(new java.awt.Dimension(388, 50));
        orderNumber.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                orderNumberMouseClicked(evt);
            }
        });
        add(orderNumber);
    }// </editor-fold>//GEN-END:initComponents

    private void orderNumberMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_orderNumberMouseClicked
    {//GEN-HEADEREND:event_orderNumberMouseClicked
        //navigator.goToOrderDetails();
       
        ordersList.goToOrderDetails();
        
    }//GEN-LAST:event_orderNumberMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel orderNumber;
    // End of variables declaration//GEN-END:variables
}
